[global]
type=global
user_agent=MIMIR-Lab-PBX

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[1000]
type=endpoint
transport=transport-udp
context=lab
disallow=all
allow=ulaw,alaw
aors=1000
auth=1000
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1000]
type=auth
auth_type=userpass
username=1000
password=lab1000

[1000]
type=aor
max_contacts=1
remove_existing=yes

[2001]
type=endpoint
transport=transport-udp
context=lab
disallow=all
allow=ulaw,alaw
aors=2001
auth=2001
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[2001]
type=auth
auth_type=userpass
username=2001
password=clarke2001

[2001]
type=aor
max_contacts=1
remove_existing=yes

[2002]
type=endpoint
transport=transport-udp
context=lab
disallow=all
allow=ulaw,alaw
aors=2002
auth=2002
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[2002]
type=auth
auth_type=userpass
username=2002
password=einstein2002

[2002]
type=aor
max_contacts=1
remove_existing=yes

[2003]
type=endpoint
transport=transport-udp
context=lab
disallow=all
allow=ulaw,alaw
aors=2003
auth=2003
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[2003]
type=auth
auth_type=userpass
username=2003
password=schrodinger2003

[2003]
type=aor
max_contacts=1
remove_existing=yes

[2004]
type=endpoint
transport=transport-udp
context=lab
disallow=all
allow=ulaw,alaw
aors=2004
auth=2004
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[2004]
type=auth
auth_type=userpass
username=2004
password=curie2004

[2004]
type=aor
max_contacts=1
remove_existing=yes

[2005]
type=endpoint
transport=transport-udp
context=lab
disallow=all
allow=ulaw,alaw
aors=2005
auth=2005
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[2005]
type=auth
auth_type=userpass
username=2005
password=bohr2005

[2005]
type=aor
max_contacts=1
remove_existing=yes

[2006]
type=endpoint
transport=transport-udp
context=lab
disallow=all
allow=ulaw,alaw
aors=2006
auth=2006
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[2006]
type=auth
auth_type=userpass
username=2006
password=tesla2006

[2006]
type=aor
max_contacts=1
remove_existing=yes
