[general]
format=wav49|gsm|wav
serveremail=pbx@mimir.local
attach=no

[default]
2001 => 2001,Arthur C. Clarke,pbx@mimir.local
2002 => 2002,Albert Einstein,pbx@mimir.local
2003 => 2003,Erwin Schrodinger,pbx@mimir.local
2004 => 2004,Marie Curie,pbx@mimir.local
2005 => 2005,Niels Bohr,pbx@mimir.local
2006 => 2006,Nikola Tesla,pbx@mimir.local
